import { Shade } from '@/types';

export const BRIGHTO_SHADES: Shade[] = [
    { id: '9000', product_id: '', name: 'Brilliant White', code: '9000', hex: '#FFFFFF', is_drum_available: true },
    { id: '9012', product_id: '', name: 'Off White', code: '9012', hex: '#FAF9F6', is_drum_available: true },
    { id: '9041', product_id: '', name: 'Ash White', code: '9041', hex: '#F2F2F2', is_drum_available: true },
    { id: '9071', product_id: '', name: 'Lavender White', code: '9071', hex: '#F4F0FF', is_drum_available: false },
    { id: '9805', product_id: '', name: 'Wisteria White', code: '9805', hex: '#FDF5E6', is_drum_available: false },
    { id: '9807', product_id: '', name: 'Twilight', code: '9807', hex: '#E6E6FA', is_drum_available: false },
    { id: '9802', product_id: '', name: 'Kitten White', code: '9802', hex: '#FFF5EE', is_drum_available: false },
    { id: '9141', product_id: '', name: 'New Ash White', code: '9141', hex: '#E8E8E8', is_drum_available: false },
    { id: '9808', product_id: '', name: 'Silver Grey', code: '9808', hex: '#C0C0C0', is_drum_available: false },
    { id: '9809', product_id: '', name: 'Shell Grey', code: '9809', hex: '#D3D3D3', is_drum_available: false },
    { id: '9803', product_id: '', name: 'Dove White', code: '9803', hex: '#F8F8F8', is_drum_available: false },
    { id: '9684', product_id: '', name: 'Goose Wing', code: '9684', hex: '#DCDCDC', is_drum_available: false },
    { id: '9681', product_id: '', name: 'Ice Grey', code: '9681', hex: '#D1D1D1', is_drum_available: false },
    { id: '9070', product_id: '', name: 'Rose White', code: '9070', hex: '#FFF0F5', is_drum_available: false },
    { id: '9043', product_id: '', name: 'Whisper', code: '9043', hex: '#F5F5F5', is_drum_available: false },
    { id: '9046', product_id: '', name: 'Dove Grey', code: '9046', hex: '#A9A9A9', is_drum_available: false },
    { id: '9001', product_id: '', name: 'Cream', code: '9001', hex: '#FFFDD0', is_drum_available: false },
    { id: '9801', product_id: '', name: 'Ivory Silk', code: '9801', hex: '#FFFFF0', is_drum_available: false },
    { id: '9040', product_id: '', name: 'Peach Cream', code: '9040', hex: '#FFEFD5', is_drum_available: false },
    { id: '9306', product_id: '', name: 'Champaign', code: '9306', hex: '#F7E7CE', is_drum_available: false },
    { id: '9048', product_id: '', name: 'Badami', code: '9048', hex: '#EEDC82', is_drum_available: false },
    { id: '9804', product_id: '', name: 'Brazil Nut', code: '9804', hex: '#A67B5B', is_drum_available: false },
    { id: '9042', product_id: '', name: 'Sand Stone', code: '9042', hex: '#C2B280', is_drum_available: false },
    { id: '9017', product_id: '', name: 'Stone', code: '9017', hex: '#8B8680', is_drum_available: false },
    { id: '9305', product_id: '', name: 'Coca Milk', code: '9305', hex: '#D2B48C', is_drum_available: false },
    { id: '9022', product_id: '', name: 'Chocolate', code: '9022', hex: '#7B3F00', is_drum_available: false },
    { id: '9045', product_id: '', name: 'Pale Peach', code: '9045', hex: '#FFDAB9', is_drum_available: false },
    { id: '9050', product_id: '', name: 'Rose Petal', code: '9050', hex: '#F7CAC9', is_drum_available: false },
    { id: '9302', product_id: '', name: 'Palm Peach Pink', code: '9302', hex: '#FFD1DC', is_drum_available: false },
    { id: '9024', product_id: '', name: 'Apricot', code: '9024', hex: '#FBCEB1', is_drum_available: false },
    { id: '9686', product_id: '', name: 'Tea Rose', code: '9686', hex: '#F4C2C2', is_drum_available: false },
    { id: '9221', product_id: '', name: 'Deep Pink', code: '9221', hex: '#FF1493', is_drum_available: false },
    { id: '9688', product_id: '', name: 'Coral Spice', code: '9688', hex: '#E2725B', is_drum_available: false },
    { id: '9015', product_id: '', name: 'Rose Pink', code: '9015', hex: '#FF66CC', is_drum_available: false },
    { id: '9009', product_id: '', name: 'Brighto Pink', code: '9009', hex: '#FF007F', is_drum_available: false },
    { id: '9300', product_id: '', name: 'Summer Pink', code: '9300', hex: '#FFB6C1', is_drum_available: false },
    { id: '9222', product_id: '', name: 'Carnival Pink', code: '9222', hex: '#E4007C', is_drum_available: false },
    { id: '9007', product_id: '', name: 'Brighto Red', code: '9007', hex: '#ED1C24', is_drum_available: false },
    { id: '9690', product_id: '', name: 'Pastle Green', code: '9690', hex: '#77DD77', is_drum_available: false },
    { id: '9506', product_id: '', name: 'Fresh Green', code: '9506', hex: '#90EE90', is_drum_available: false },
    { id: '9689', product_id: '', name: 'Pine Frost', code: '9689', hex: '#E0F2F1', is_drum_available: false },
    { id: '9006', product_id: '', name: 'Lime Green', code: '9006', hex: '#32CD32', is_drum_available: false },
    { id: '9010', product_id: '', name: 'Melody Green', code: '9010', hex: '#98FF98', is_drum_available: false },
    { id: '9027', product_id: '', name: 'Apple Green', code: '9027', hex: '#8DB600', is_drum_available: false },
    { id: '9004', product_id: '', name: 'Brighto Green', code: '9004', hex: '#008000', is_drum_available: false },
    { id: '9510', product_id: '', name: 'Forest Green', code: '9510', hex: '#228B22', is_drum_available: false },
    { id: '9513', product_id: '', name: 'Green Summit', code: '9513', hex: '#004225', is_drum_available: false },
    { id: '9035', product_id: '', name: 'Leaf Green', code: '9035', hex: '#3CB371', is_drum_available: false },
    { id: '9011', product_id: '', name: 'Lilac', code: '9011', hex: '#C8A2C8', is_drum_available: false },
    { id: '9683', product_id: '', name: 'Soothing Lilac', code: '9683', hex: '#E6E6FA', is_drum_available: false },
    { id: '9501', product_id: '', name: 'Purple', code: '9501', hex: '#800080', is_drum_available: false },
    { id: '9014', product_id: '', name: 'Ice Blue', code: '9014', hex: '#AFEEEE', is_drum_available: false },
    { id: '9002', product_id: '', name: 'Light Blue', code: '9002', hex: '#ADD8E6', is_drum_available: false },
    { id: '9008', product_id: '', name: 'Brighto Blue', code: '9008', hex: '#0000FF', is_drum_available: false },
    { id: '9502', product_id: '', name: 'Peacock Plum', code: '9502', hex: '#BDB76B', is_drum_available: false },
    { id: '9503', product_id: '', name: 'Fluorite', code: '9503', hex: '#996515', is_drum_available: false },
    { id: '9508', product_id: '', name: 'Electric Blue', code: '9508', hex: '#7DF9FF', is_drum_available: false },
    { id: '9072', product_id: '', name: 'Cockleshell', code: '9072', hex: '#FFE5B4', is_drum_available: false },
    { id: '9303', product_id: '', name: 'Zephyr', code: '9303', hex: '#778899', is_drum_available: false },
    { id: '9687', product_id: '', name: 'Cameo', code: '9687', hex: '#D2B48C', is_drum_available: false },
    { id: '9692', product_id: '', name: 'Parasol', code: '9692', hex: '#EEDC82', is_drum_available: false },
    { id: '9332', product_id: '', name: 'Classical', code: '9332', hex: '#F5F5DC', is_drum_available: false },
    { id: '9005', product_id: '', name: 'Orange', code: '9005', hex: '#FFA500', is_drum_available: false },
    { id: '9698', product_id: '', name: 'Terracotta', code: '9698', hex: '#E2725B', is_drum_available: false },
    { id: '9810', product_id: '', name: 'Black', code: '9810', hex: '#000000', is_drum_available: false }
];
